# GitHub Pages Configuration for RS-ModCubes

title: RS-ModCubes
description: Self-Reconfigurable, Scalable Modular Cubic Robots for Underwater Operations
url: "https://jiaxi-zheng.github.io"
baseurl: "/ModCube.github.io"

# Theme
theme: just-the-docs

# Author information
author:
  name: Jiaxi Zheng
  email: jiaxi.zheng@example.com

# Social links
github_username: jiaxi-zheng

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Just The Docs Configuration
color_scheme: nil
search_enabled: true
search:
  heading_level: 2
  previews: 2
  preview_words_before: 3
  preview_words_after: 3
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Navigation Structure
nav_sort: case_insensitive
nav_external_links:
  - title: GitHub Repository
    url: https://github.com/jiaxi-zheng/ModCube.github.io
    hide_icon: false

# Footer
footer_content: "Copyright &copy; 2024 Jiaxi Zheng. Distributed by an <a href=\"https://github.com/jiaxi-zheng/ModCube.github.io/tree/main/LICENSE\">MIT license.</a>"

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Collections
collections:
  tutorials:
    output: true
    permalink: /:collection/:name/
  examples:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "tutorials"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "examples"
    values:
      layout: "page"